# Generated by Django 4.0.3 on 2023-07-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='课程名称')),
                ('teacher_name', models.CharField(max_length=32, verbose_name='讲师')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('create_time', models.DateField(verbose_name='入社时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('banji', models.CharField(max_length=32, verbose_name='班级')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '已签到'), (0, '未签到')], verbose_name='签到情况')),
                ('time', models.DateField(verbose_name='签到时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='学生')),
            ],
        ),
    ]
